config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "main#welcome"
  get 'app', to: 'main#index'
  resources :tasks do
    get 'edit_desc', to: 'tasks#edit_desc', on: :member
    post 'edit_desc', to: 'tasks#update_desc', on: :member
  end
  resources :groups
  resources :lists
  resources :subcategories
  resources :main do
    post 'toggle', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :lists
  belongs_to :user

  validates :name, length: {minimum: 2}, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :subcategories

  validates :name, length: {minimum: 2}, presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :list
  belongs_to :user
  has_many :tasks

  validates :name, length: {minimum: 2}, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :subcategory
  belongs_to :user

  validates :name, length: {minimum: 2}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :groups
  has_many :lists
  has_many :subcategories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group_id, only: [:edit, :update, :destroy]
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    @group.save
    if @group.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end
  def edit
  end

  def update
    if @group.update(group_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def destroy
    @group.lists.each do |list|
      subcategories = list.subcategories
      subcategories.each do |sub|
        sub.tasks.destroy_all
      end
      list.subcategories.destroy_all
    end
    @group.lists.destroy_all
    @group.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_group_id
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list_id, only: [:edit, :update, :destroy, :show]

  def show
  end

  def new
    @list = List.new
    @groups = Group.all
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @group = @list.group
      @list.save
    if @list
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end
  def edit
  end

  def update
    if @list.update(list_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def destroy
    @list.subcategories.each do |sub|
      sub.tasks.destroy_all
    end
    @list.subcategories.destroy_all
    @list.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_list_id
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:group_id, :name)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!, only: [:welcome]
  before_action :verify_authenticity_token, except: [:toggle]
  def index
    @groups = current_user.groups
    @lists = current_user.lists
    @subcategories = current_user.subcategories
    @tasks = current_user.tasks
  end

  def welcome
  end

  def toggle
    @task = Task.find(params[:id])
    @task.update(done: !@task.done)
    @task.save
    head :ok
  end
end

app/controllers/subcategories_controller.rb
# frozen_string_literal: true

class SubcategoriesController < ApplicationController
  before_action :set_sub_id, only: [:edit, :update, :destroy]
  def new
    @subcategory = Subcategory.new
    @lists = List.all
  end

  def create
    @subcategory = Subcategory.new(sub_params)
    @subcategory.user = current_user
    @list = @subcategory.list
    @subcategory.save
    if @subcategory
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end
  def edit
  end

  def update
    if @subcategory.update(sub_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def destroy
    @subcategory.tasks.destroy_all
    @subcategory.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_sub_id
    @subcategory = Subcategory.find(params[:id])
  end

  def sub_params
    params.require(:subcategory).permit(:list_id, :name)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task_id, only: [:edit, :update, :destroy, :show, :edit_desc, :update_desc]

  def show
  end
  def new
    @task = Task.new
    @subcategories = Subcategory.all
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @subcategory = @task.subcategory
    @task.save
    if @task.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def edit
    @subcategories = Subcategory.all
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def edit_desc
  end

  def update_desc
    if @task.update(task_description_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      redirect_to app_path, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_task_id
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :subcategory_id)
  end

  def task_description_params
    params.require(:task).permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/turbo_stream_action_helper.rb
# frozen_string_literal: true

module TurboStreamActionsHelper
  def action_assign
    turbo_stream_action_tag :action_assign
  end
end

Turbo::Streams::TagBuilder.prepend(TurboStreamActionsHelper)

app/helpers/turbo_stream_actions_helper.rb
# frozen_string_literal: true

module TurboStreamActionsHelper
  def action_assign
    turbo_stream_action_tag :action_assign
  end

  def reload_signs
    turbo_stream_action_tag :reload_signs
  end
end

Turbo::Streams::TagBuilder.prepend(TurboStreamActionsHelper)

app/views/groups/_group.html.erb
<%= turbo_frame_tag group do %>
  <div class="opt-tg">
    <details>
      <summary>
        <%= group.name %>
        <div class="action">
          <div class="add"><%= link_to 'add', new_list_path, data: { turbo_frame: "newList#{group.id}" }, class: 'material-symbols-outlined hover smaller-icon' %></div>
          <div class="remove"><%= link_to 'remove', '#', data: { turbo_frame: "newList#{group.id}" }, class: 'material-symbols-outlined hover smaller-icon' %></div>
          <div class="options hover">
            <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined smaller-icon'%>
            <div class="options-open">
              <%= link_to 'edit', edit_group_path(group), data: { turbo_frame: "editGroup#{group.id}"}, class: 'material-symbols-outlined smaller-icon scale-up edit'%>
              <%= link_to 'delete', group_path(group), data: { turbo_method: :delete, turbo_frame: "_top" }, class: 'material-symbols-outlined smaller-icon scale-up delete'%>
            </div>
          </div>
        </div>
      </summary>
      <%= turbo_frame_tag "lists#{group.id}" do %>
        <% group.lists.each do |list| %>
          <%= render partial: list, locals: { list: list } %>
        <% end %>
      <% end %>
      <%= turbo_frame_tag "newList#{group.id}" do %>
      <% end %>
    </details>
  </div>
<% end %>

app/views/groups/create.turbo_stream.erb
<%= turbo_stream.append "groups", @group %>
<%= turbo_stream.update "newGroup", "" %>
<%= turbo_stream.action_assign %>
<%= turbo_stream.reload_signs %>

app/views/groups/destroy.turbo_stream.erb
<%= turbo_stream.remove @group %>

app/views/groups/edit.html.erb
<%= turbo_frame_tag @group do %>
  <%= form_with(model: @group, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :name, placeholder: 'New group...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<%= turbo_frame_tag "newGroup" do %>
  <%= form_with(model: @group, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :name, placeholder: 'New group...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/groups/update.turbo_stream.erb
<%= turbo_stream.replace @group %>
<%= turbo_stream.action_assign %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.typekit.net/yqx2xsr.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<%= turbo_frame_tag list do %>
  <div class="item opt-tg">
    <%= link_to list.name, list_path(list), data: { turbo_frame: "middle-panel"}, id: 'list_tg' %>
    <div class="options hover">
      <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined smaller-icon'%>
      <div class="options-open">
        <%= link_to 'edit', edit_list_path(list), data: { turbo_frame: "editList#{list.id}"}, class: 'material-symbols-outlined smaller-icon scale-up edit'%>
        <%= link_to 'delete', list_path(list), data: { turbo_method: :delete, turbo_frame: "_top" }, class: 'material-symbols-outlined smaller-icon scale-up delete'%>
      </div>
    </div>
  </div>
<% end %>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.append "lists#{@group.id}", @list %>
<%= turbo_stream.update "newList#{@group.id}", "" %>
<%= turbo_stream.action_assign %>
<%= turbo_stream.reload_signs %>

app/views/lists/destroy.turbo_stream.erb
<%= turbo_stream.remove @list %>

app/views/lists/edit.html.erb
<%= turbo_frame_tag @list do %>
  <%= form_with(model: @list, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :name, placeholder: 'Edit list...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/lists/new.html.erb
<% @groups.each do |group| %>
  <%= turbo_frame_tag "newList#{group.id}" do %>
    <%= form_with(model: @list, local: true, class: 'form-container') do |f| %>
      <%= f.hidden_field 'group_id', value: group.id %>
      <%= f.text_field :name, placeholder: 'New list...', autocomplete: "off", spellcheck: false, autofocus: true %>
      <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
    <% end %>
  <% end %>
<% end %>

app/views/lists/show.html.erb
<%= turbo_frame_tag 'middle-panel' do %>
  <div class="nav">
    <div class="text">
      <span class="material-symbols-outlined collapse-m-p">
        close
      </span>
      <h3 class="hug">Tasks</h3>
    </div>
    <div class="action">
      <div class="add_outer"><%= link_to 'add', new_subcategory_path, data: { turbo_frame: "newSub#{@list.id}" }, class: 'material-symbols-outlined hover bigger-icon' %></div>
      <div class="remove_outer"><%= link_to 'remove', list_path, data: { turbo_frame: "newSub#{@list.id}" }, class: 'material-symbols-outlined hover bigger-icon' %></div>
    </div>
  </div>
  <div class="content">
    <div class="tags">
      <div class="tag">
        <%= @list.group.name %>
      </div>
      <div class="tag">
        <%= @list.name %>
      </div>
    </div>
    <div class="lists">
      <%= turbo_frame_tag "subcategories#{@list.id}" do %>
        <% @list.subcategories.each do |subcategory| %>
          <%= render partial: subcategory, locals: { subcategory: subcategory } %>
        <% end %>
      <% end %>
    </div>
    <%= turbo_frame_tag "newSub#{@list.id}" do %>
    <% end %>
  </div>
<% end %>

app/views/lists/update.turbo_stream.erb
<%= turbo_stream.replace @list %>
<%= turbo_stream.action_assign %>

app/views/main/index.html.erb
<section id="main">
  <section id="left-panel">
    <div class="nav">
      <div class="text">
        <h3 class="hug collapse">Groups</h3>
      </div>
      <div class="action">
        <div class="add_outer"><%= link_to 'add', new_group_path, data: { turbo_frame: "newGroup" }, class: 'material-symbols-outlined hover bigger-icon' %></div>
        <div class="remove_outer"><%= link_to 'remove', '#', data: { turbo_frame: "newGroup" }, class: 'material-symbols-outlined hover bigger-icon' %></div>
        <div class="action-more hover">
          <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined bigger-icon'%>
          <div class="action-more-open">
            <%= link_to 'person', '#', data: { turbo: false }, class: 'material-symbols-outlined bigger-icon scale-up'%>
            <%= link_to 'logout', destroy_user_session_path, data: { turbo_method: :delete }, class: 'material-symbols-outlined bigger-icon scale-up'%>
          </div>
        </div>
      </div>
    </div>
    <div class="content">
      <div class="lists">
        <%= turbo_frame_tag "groups" do %>
          <% @groups.each do |group| %>
            <%= render partial: 'groups/group', locals: { group: group } %>
          <% end %>
        <% end %>
      </div>
      <%= turbo_frame_tag 'newGroup' do %>
      <% end %>
    </div>
  </section>
  <%= turbo_frame_tag 'middle-panel' do %>
  <% end %>
  <%= turbo_frame_tag 'right-panel' do %>
  <% end %>
</section>

app/views/main/welcome.html.erb
<section id="welcome">
  <h1>MiniTODO</h1>
  <h3>Your safe place to organize everything</h3>
  <%= link_to 'Start', app_path, class: 'run-btn' %>
</section>

app/views/subcategories/_subcategory.html.erb
<%= turbo_frame_tag subcategory do %>
  <div class="list">
    <div class="opt-tg">
      <details>
        <summary>
          <%= subcategory.name %>
          <div class="action">
            <div class="add"><%= link_to 'add', new_task_path, data: { turbo_frame: "newTask#{subcategory.id}" }, class: 'material-symbols-outlined hover smaller-icon' %></div>
            <div class="remove"><%= link_to 'remove', list_path(subcategory.list), data: { turbo_frame: "newTask#{subcategory.id}" }, class: 'material-symbols-outlined hover smaller-icon' %></div>
            <div class="options hover">
              <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined smaller-icon'%>
              <div class="options-open">
                <%= link_to 'edit', edit_subcategory_path(subcategory), data: { turbo_frame: "editSub#{subcategory.id}"}, class: 'material-symbols-outlined smaller-icon scale-up edit'%>
                <%= link_to 'delete', subcategory_path(subcategory), data: { turbo_method: :delete, turbo_frame: "_top" }, class: 'material-symbols-outlined smaller-icon scale-up delete'%>
              </div>
            </div>
          </div>
        </summary>
        <div id="items">
          <%= turbo_frame_tag "tasks#{subcategory.id}" do %>
            <% subcategory.tasks.each do |task| %>
              <%= render partial: task, locals: { task: task } %>
            <% end %>
          <% end %>
          <%= turbo_frame_tag "newTask#{subcategory.id}" do %>
          <% end %>
        </div>
      </details>
    </div>
  </div>
<% end %>

app/views/subcategories/create.turbo_stream.erb
<%= turbo_stream.append "subcategories#{@list.id}", @subcategory %>
<%= turbo_stream.update "newSub#{@list.id}", "" %>
<%= turbo_stream.action_assign %>
<%= turbo_stream.reload_signs %>

app/views/subcategories/destroy.turbo_stream.erb
<%= turbo_stream.remove @subcategory %>

app/views/subcategories/edit.html.erb
<%= turbo_frame_tag @subcategory do %>
  <%= form_with(model: @subcategory, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :name, placeholder: 'Edit subcategory...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/subcategories/new.html.erb
<% @lists.each do |list| %>
  <%= turbo_frame_tag "newSub#{list.id}" do %>
    <%= form_with(model: @subcategory, local: true, class: 'form-container') do |f| %>
      <%= f.hidden_field 'list_id', value: list.id %>
      <%= f.text_field :name, placeholder: 'New subcategory...', autocomplete: "off", spellcheck: false, autofocus: true %>
      <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
    <% end %>
  <% end %>
<% end %>

app/views/subcategories/update.turbo_stream.erb
<%= turbo_stream.replace @subcategory %>
<%= turbo_stream.action_assign %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag task do %>
  <div class="item opt-tg">
    <div class="cont <%= 'const-done' if task.done %>">
      <%= check_box_tag 'done', task.id, task.done, id: "task_#{task.id}" %>
      <%= link_to task.name, task_path(task), data: { turbo_frame: "right-panel"}, id: 'task_tg' %>
    </div>
    <div class="options hover">
      <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined smaller-icon'%>
      <div class="options-open">
        <%= link_to 'edit', edit_task_path(task), class: 'material-symbols-outlined smaller-icon scale-up edit'%>
        <%= link_to 'delete', task_path(task), data: { turbo_method: :delete }, class: 'material-symbols-outlined smaller-icon scale-up delete'%>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_task_desc.html.erb
<div class="desc">
  <p><%= task.description %></p>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "tasks#{@subcategory.id}", @task %>
<%= turbo_stream.update "newTask#{@subcategory.id}", "" %>
<%= turbo_stream.action_assign %>
<%= turbo_stream.reload_signs %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove @task %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag @task do %>
  <%= form_with(model: @task, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :name, placeholder: 'Edit task...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/tasks/edit_desc.html.erb
<%= turbo_frame_tag "desc#{@task.id}" do %>
  <%= form_with(model: @task, url: edit_desc_task_path, method: :post, local: true, class: 'form-container') do |f| %>
    <%= f.text_field :description, placeholder: 'Edit description...', autocomplete: "off", spellcheck: false, autofocus: true %>
    <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<% @subcategories.each do |sub| %>
  <%= turbo_frame_tag "newTask#{sub.id}" do %>
    <%= form_with(model: @task, local: true, class: 'form-container') do |f| %>
      <%= f.hidden_field 'subcategory_id', value: sub.id %>
      <%= f.text_field :name, placeholder: 'New task...', autocomplete: "off", spellcheck: false, autofocus: true %>
      <%= f.submit value: 'Add', data: {turbo_frame: "_top"}, hidden: true %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/show.html.erb
<%= turbo_frame_tag "right-panel" do %>
  <div class="nav">
    <div class="text">
      <span class="material-symbols-outlined collapse-r-p">
        close
      </span>
      <h3 class="hug">Task details</h3>
    </div>
    <div class="action-more hover">
      <%= link_to "more_horiz", '#', data: { turbo: false }, class: 'material-symbols-outlined bigger-icon'%>
      <div class="action-more-open">
        <%= link_to 'edit', edit_desc_task_path, data: { turbo_frame: "desc#{@task.id}" }, class: 'material-symbols-outlined bigger-icon scale-up'%>
        <%= link_to 'delete', task_path(@task), data: { turbo_method: :delete, turbo_frame: "_top" }, class: 'material-symbols-outlined bigger-icon scale-up delete'%>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="title">
      <h4><%= @task.name %></h4>
    </div>
    <%= turbo_frame_tag "desc#{@task.id}" do %>
      <%= render partial: 'task_desc', locals: { task: @task } %>
    <% end %>
    <div class="tags">
      <div class="tag">
        <%= @task.subcategory.name %>
      </div>
      <div class="tag" style="background-color: <%= @task.done ? '#9EF597' : '#84D5F5' %>;">
        <%= @task.done ? "Done" : "Ongoing" %>
      </div>
    </div>
    <div class="user-info">
    </div>
  </div>
<% end %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace @task %>
<%= turbo_stream.action_assign %>

app/views/tasks/update_desc.turbo_stream.erb
<%= turbo_stream.replace("desc#{@task.id}", partial: 'task_desc', locals: { task: @task }) %>
<%= turbo_stream.action_assign %>